apiVersion: metaspore/v1
kind: TrainingJob
metadata:
  name: SampleGeneration
  category: Dataset/SampleGeneration

spec:
  logging:
    loglevel: debug

  init_spark:
    session_conf:
      app_name: 'Ecommerce Generating Samples'
      local: True
      worker_count: 1
      worker_cpu: 2
      server_count: 1
      server_cpu: 2
      batch_size: 256
      worker_memory: '4G'
      server_memory: '4G'
      coordinator_memory: '2G'
    extended_conf:
      spark.network.timeout: '500'
      spark.ui.showConsoleProgress: 'true'
      spark.kubernetes.executor.deleteOnTermination: 'true'
      spark.jars.packages: 'org.mongodb.spark:mongo-spark-connector_2.12:3.0.1'
      spark.default.parallelism: '10'
      spark.sql.shuffle.partitions: '10'

  load_dataset: 
    user_path: /opt/volumes/output/data/amazon_fashion_user.parquet
    item_path: /opt/volumes/output/data/amazon_fashion_item.parquet
    interaction_path: /opt/volumes/output/data/amazon_fashion_interaction.parquet
    fmt: parquet

  join_dataset:
    join_on: 
      user_key: user_id
      item_key: item_id
      timestamp: timestamp
    user_bhv_seq:
      max_len: 10
    negative_sample:
      sample_ratio: 3

  gen_feature:
    reserve_only_cate_cols: True

  gen_sample:
    - model_type: ctr_nn
      split_test: 0.15
      shuffle: True
      fmt: parquet
      train_path: /opt/volumes/output/data/ctr/nn/train.parquet
      test_path: /opt/volumes/output/data/ctr/nn/test.parquet

    - model_type: ctr_gbm
      split_test: 0.15
      use_shuffle: True
      fmt: parquet
      combine_schema:
        user_cols: [user_id]
        item_cols: [item_id, category]
        combine_cols: []
      train_path: /opt/volumes/output/data/ctr/gbm/train.parquet
      test_path: /opt/volumes/output/data/ctr/gbm/test.parquet

    - model_type: match_nn
      split_test: 0.15
      shuffle: True
      fmt: parquet
      train_path: /opt/volumes/output/data/match/nn/train.parquet
      test_path: /opt/volumes/output/data/match/nn/test.parquet
      item_path: /opt/volumes/output/data/match/nn/item.parquet

    - model_type: match_icf
      split_test: 0.15
      shuffle: True
      fmt: parquet
      train_path: /opt/volumes/output/data/match/icf/train.parquet
      test_path: /opt/volumes/output/data/match/icf/test.parquet

  dump_nn_feature:
    mongodb:
      uri: mongodb://root:test_mongodb_123456@localhost:27018/?authSource=admin
      database: jpa
      write_mode: overwrite
      index_fields: []
      index_unique: False
    tables:
      - feature_column: 
          - user_id
          - user_bhv_item_seq
        mongo_collection: amazonfashion_user_feature
        drop_duplicates_by: [user_id]
      - feature_column: 
          - item_id
          - brand
          - category
        mongo_collection: amazonfashion_item_feature
        drop_duplicates_by: [item_id]
      - feature_column: 
          - item_id
          - brand
          - category
          - title
          - description
          - image
          - url
          - price
        mongo_collection: amazonfashion_item_summary
        drop_duplicates_by: [item_id]

  dump_lgb_feaure:
    mongodb:
      uri: mongodb://root:test_mongodb_123456@localhost:27018/?authSource=admin
      database: jpa
      write_mode: overwrite
      index_fields: []
      index_unique: False
    tables:
      - feature_column: user_cols
        mongo_collection: amazonfashion_user_lgb_feature
      - feature_column: item_cols
        mongo_collection: amazonfashion_item_lgb_feature
  