## spark session
app_name: 'SimpleX Demo'
local: False
worker_count: 4
server_count: 4
batch_size: 512
worker_memory: '10G'
server_memory: '10G'
coordinator_memory: '10G'

## datasets
train_path: ${MY_S3_BUCKET}/movielens/match/num_negs_100/train.parquet
test_path: ${MY_S3_BUCKET}/movielens/match/num_negs_100/test.parquet
item_path: ${MY_S3_BUCKET}/movielens/match/num_negs_100/item.parquet
swing_out_path: ${MY_S3_BUCKET}/movielens/mango/swing.parquet/

## swing model configuration
user_id_column_name: user_id
item_id_column_name: movie_id
last_item_col_name: last_movie
behavior_column_name: label
behavior_filter_value: '1'
key_column_name: key
value_column_name: value

## model hyper params
use_plain_weight: False
smoothing_coefficient: 1.0
max_recommendation_count: 20

