## spark session
app_name: 'WideDeep Demo'
local: True
worker_count: 4
server_count: 2
batch_size: 60
worker_memory: '5G'
server_memory: '5G'
coordinator_memory: '5G'

## datasets
train_path: ${MY_S3_BUCKET}/movielens/rank/train.parquet
test_path: ${MY_S3_BUCKET}/movielens/rank/test.parquet

## model configurations
column_name_path: ${MY_S3_BUCKET}/movielens/schema/widedeep/column_schema
combine_schema_path: ${MY_S3_BUCKET}/movielens/schema/widedeep/combine_column_schema
wide_combine_schema_path: ${MY_S3_BUCKET}/movielens/schema/widedeep/wide_combine_column_schema

model_in_path: null
model_out_path: ${MY_S3_BUCKET}/movielens/model/widedeep/model_out/
model_export_path: ${MY_S3_BUCKET}/movielens/model/widedeep/model_export/
model_version: '0.1'
experiment_name: movie_lens_wdl
input_label_column_index: 0

## model hyper params
embedding_size: 10
net_dropout: 0.0
adam_learning_rate: 0.00001
ftrl_learning_rate: 0.02
ftrl_smothing_rate: 1.0
ftrl_l1_regularization: 1.0
ftrl_l2_regularization: 1.0
training_epoches: 1
shuffle_training_dataset: False
dnn_hidden_units: [1024,512,256,128]
