## spark session
app_name: 'CTR Demo AutoInt'
local: False
worker_count: 4
server_count: 4
batch_size: 50
worker_memory: '10G'
server_memory: '10G'
coordinator_memory: '10G'

## datasets
train_path: ${MY_S3_BUCKET}/criteo_x1/train_5.parquet
test_path: ${MY_S3_BUCKET}/criteo_x1/test_1.parquet

## model configurations
column_name_path: ${MY_S3_BUCKET}/schema/column_name_demo.txt
combine_schema_path: ${MY_S3_BUCKET}/schema/combine_schema_demo.txt

model_in_path: null
model_out_path: ${MY_S3_BUCKET}/movielens/model/autoint/model_out/criteo_d5/
model_export_path: ${MY_S3_BUCKET}/movielens/model/autoint/model_export/criteo_d5/
model_version: '0.1'
experiment_name: criteo_autoint_d5
input_label_column_index: 0
metric_update_interval: 100

## model hyper params
use_wide: True
use_residual: True
use_scale: False
embedding_dim: 16
adam_learning_rate: 0.0001
ftrl_l1: 1.0
ftrl_l2: 120.0
ftrl_alpha: 0.01
ftrl_beta: 1.0
dnn_hidden_units: [1024, 1024, 1024, 1024, 1024]
sparse_init_var: 0.01
dnn_hidden_activations: ReLU
use_bias: True
batch_norm: False
net_dropout: null
net_regularizer: null
attention_layers: 1
num_heads: 1
attention_dim: 64
layer_norm: False