apiVersion: metaspore/v1
kind: OnlineFlow
metadata:
  name: online_sagemaker_flow
spec:
  services:
    mongo:
      kind: MongoDB
      serviceName: mongo
      collection: [ {{mongodb_db}} ]
      options:
        uri: {{mongodb_uri}}
  source:
    user_key_name: {{user_key}} 
    item_key_name: {{item_key}} 
    user_item_ids_name: {{user_item_ids}} 
    user_item_ids_split: {{user_item_ids_spilt}}
    user:
      table: {{user_feature_collection}} 
      serviceName: mongo
      collection: {{mongodb_db}}
      columns: {{user_cloumns}} 
    item:
      table: {{item_feature_collection}} 
      serviceName: mongo
      collection: {{mongodb_db}}
      columns: {{item_cloumns}} 
    summary:
      table: {{item_summary_collection}} 
      serviceName: mongo
      collection: {{mongodb_db}}
      columns: {{summary_cloumns}} 
      max_reservation: {{max_reservation}} 
    request: {{request_cloumns}} 
  random_models:
    - name: pop
      bound: 10
      model_info:
      recallService: recall_pop
      keyName: key
      valueName: value_list
      source:
        table: {{match_popular_dump_collection}}
        serviceName: mongo
        collection: {{mongodb_db}}
  cf_models:
    - name: swing
      recallService: recall_swing
      relatedService: related_swing
      keyName: key
      valueName: value
      source:
        table: {{match_itemcf_dump_collection}}
        serviceName: mongo
        collection: {{mongodb_db}}
  rank_models:
    - name: widedeep
      # model: {{rank_deepctr_online_name}}
      model: widedeep
      rankService: rank_widedeep
      column_info:
        - dnn_sparse: {{rank_model_dnn_sparse}}
        - lr_sparse: {{rank_model_lr_sparse}}
      cross_features: {{rank_model_cross_features}}
  experiments:
    - name: experiment.recall.swing
      then: [ recall_swing ]
    - name: experiment.related.swing
      then: [ related_swing ]
    - name: experiment.recall.pop
      then: [ recall_pop ]
    - name: experiment.rank.widedeep
      then: [ rank_widedeep ]
  layers:
    - name: layer.recall
      data:
        experiment.recall.swing: 1.0
    - name: layer.related
      data:
        experiment.related.swing: 1.0
    - name: layer.rank
      data:
        experiment.rank.widedeep: 1.0
  scenes:
    - name: guess-you-like
      layers: [ layer.recall, layer.rank ]
      additionalRecalls: [ pop ]
    - name: looked-and-looked
      layers: [ layer.related, layer.rank ]
      additionalRecalls: [ pop ]