# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hf_preprocessor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15hf_preprocessor.proto\x12\x12multimodal.service\"\x9d\x02\n\x12HfTokenizerRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12J\n\nparameters\x18\x03 \x03(\x0b\x32\x36.multimodal.service.HfTokenizerRequest.ParametersEntry\x12\x44\n\x07payload\x18\x05 \x03(\x0b\x32\x33.multimodal.service.HfTokenizerRequest.PayloadEntry\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a.\n\x0cPayloadEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\"\x80\x02\n\x13HfTokenizerResponse\x12\x45\n\x07payload\x18\x01 \x03(\x0b\x32\x34.multimodal.service.HfTokenizerResponse.PayloadEntry\x12\x43\n\x06\x65xtras\x18\x03 \x03(\x0b\x32\x33.multimodal.service.HfTokenizerResponse.ExtrasEntry\x1a.\n\x0cPayloadEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\x1a-\n\x0b\x45xtrasEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"?\n\x16HfTokenizerPushRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x11\n\tmodel_url\x18\x02 \x01(\t\"6\n\x17HfTokenizerPushResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t2\xe0\x01\n\x0eHfPreprocessor\x12`\n\x0bHfTokenizer\x12&.multimodal.service.HfTokenizerRequest\x1a\'.multimodal.service.HfTokenizerResponse\"\x00\x12l\n\x0fHfTokenizerPush\x12*.multimodal.service.HfTokenizerPushRequest\x1a+.multimodal.service.HfTokenizerPushResponse\"\x00\x42Z\n/com.dmetasoul.metaspore.demo.multimodal.serviceB\x1aHfPreprocessorServiceProtoP\x01\xf8\x01\x01\xa2\x02\x05SPOREb\x06proto3')



_HFTOKENIZERREQUEST = DESCRIPTOR.message_types_by_name['HfTokenizerRequest']
_HFTOKENIZERREQUEST_PARAMETERSENTRY = _HFTOKENIZERREQUEST.nested_types_by_name['ParametersEntry']
_HFTOKENIZERREQUEST_PAYLOADENTRY = _HFTOKENIZERREQUEST.nested_types_by_name['PayloadEntry']
_HFTOKENIZERRESPONSE = DESCRIPTOR.message_types_by_name['HfTokenizerResponse']
_HFTOKENIZERRESPONSE_PAYLOADENTRY = _HFTOKENIZERRESPONSE.nested_types_by_name['PayloadEntry']
_HFTOKENIZERRESPONSE_EXTRASENTRY = _HFTOKENIZERRESPONSE.nested_types_by_name['ExtrasEntry']
_HFTOKENIZERPUSHREQUEST = DESCRIPTOR.message_types_by_name['HfTokenizerPushRequest']
_HFTOKENIZERPUSHRESPONSE = DESCRIPTOR.message_types_by_name['HfTokenizerPushResponse']
HfTokenizerRequest = _reflection.GeneratedProtocolMessageType('HfTokenizerRequest', (_message.Message,), {

  'ParametersEntry' : _reflection.GeneratedProtocolMessageType('ParametersEntry', (_message.Message,), {
    'DESCRIPTOR' : _HFTOKENIZERREQUEST_PARAMETERSENTRY,
    '__module__' : 'hf_preprocessor_pb2'
    # @@protoc_insertion_point(class_scope:multimodal.service.HfTokenizerRequest.ParametersEntry)
    })
  ,

  'PayloadEntry' : _reflection.GeneratedProtocolMessageType('PayloadEntry', (_message.Message,), {
    'DESCRIPTOR' : _HFTOKENIZERREQUEST_PAYLOADENTRY,
    '__module__' : 'hf_preprocessor_pb2'
    # @@protoc_insertion_point(class_scope:multimodal.service.HfTokenizerRequest.PayloadEntry)
    })
  ,
  'DESCRIPTOR' : _HFTOKENIZERREQUEST,
  '__module__' : 'hf_preprocessor_pb2'
  # @@protoc_insertion_point(class_scope:multimodal.service.HfTokenizerRequest)
  })
_sym_db.RegisterMessage(HfTokenizerRequest)
_sym_db.RegisterMessage(HfTokenizerRequest.ParametersEntry)
_sym_db.RegisterMessage(HfTokenizerRequest.PayloadEntry)

HfTokenizerResponse = _reflection.GeneratedProtocolMessageType('HfTokenizerResponse', (_message.Message,), {

  'PayloadEntry' : _reflection.GeneratedProtocolMessageType('PayloadEntry', (_message.Message,), {
    'DESCRIPTOR' : _HFTOKENIZERRESPONSE_PAYLOADENTRY,
    '__module__' : 'hf_preprocessor_pb2'
    # @@protoc_insertion_point(class_scope:multimodal.service.HfTokenizerResponse.PayloadEntry)
    })
  ,

  'ExtrasEntry' : _reflection.GeneratedProtocolMessageType('ExtrasEntry', (_message.Message,), {
    'DESCRIPTOR' : _HFTOKENIZERRESPONSE_EXTRASENTRY,
    '__module__' : 'hf_preprocessor_pb2'
    # @@protoc_insertion_point(class_scope:multimodal.service.HfTokenizerResponse.ExtrasEntry)
    })
  ,
  'DESCRIPTOR' : _HFTOKENIZERRESPONSE,
  '__module__' : 'hf_preprocessor_pb2'
  # @@protoc_insertion_point(class_scope:multimodal.service.HfTokenizerResponse)
  })
_sym_db.RegisterMessage(HfTokenizerResponse)
_sym_db.RegisterMessage(HfTokenizerResponse.PayloadEntry)
_sym_db.RegisterMessage(HfTokenizerResponse.ExtrasEntry)

HfTokenizerPushRequest = _reflection.GeneratedProtocolMessageType('HfTokenizerPushRequest', (_message.Message,), {
  'DESCRIPTOR' : _HFTOKENIZERPUSHREQUEST,
  '__module__' : 'hf_preprocessor_pb2'
  # @@protoc_insertion_point(class_scope:multimodal.service.HfTokenizerPushRequest)
  })
_sym_db.RegisterMessage(HfTokenizerPushRequest)

HfTokenizerPushResponse = _reflection.GeneratedProtocolMessageType('HfTokenizerPushResponse', (_message.Message,), {
  'DESCRIPTOR' : _HFTOKENIZERPUSHRESPONSE,
  '__module__' : 'hf_preprocessor_pb2'
  # @@protoc_insertion_point(class_scope:multimodal.service.HfTokenizerPushResponse)
  })
_sym_db.RegisterMessage(HfTokenizerPushResponse)

_HFPREPROCESSOR = DESCRIPTOR.services_by_name['HfPreprocessor']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n/com.dmetasoul.metaspore.demo.multimodal.serviceB\032HfPreprocessorServiceProtoP\001\370\001\001\242\002\005SPORE'
  _HFTOKENIZERREQUEST_PARAMETERSENTRY._options = None
  _HFTOKENIZERREQUEST_PARAMETERSENTRY._serialized_options = b'8\001'
  _HFTOKENIZERREQUEST_PAYLOADENTRY._options = None
  _HFTOKENIZERREQUEST_PAYLOADENTRY._serialized_options = b'8\001'
  _HFTOKENIZERRESPONSE_PAYLOADENTRY._options = None
  _HFTOKENIZERRESPONSE_PAYLOADENTRY._serialized_options = b'8\001'
  _HFTOKENIZERRESPONSE_EXTRASENTRY._options = None
  _HFTOKENIZERRESPONSE_EXTRASENTRY._serialized_options = b'8\001'
  _HFTOKENIZERREQUEST._serialized_start=46
  _HFTOKENIZERREQUEST._serialized_end=331
  _HFTOKENIZERREQUEST_PARAMETERSENTRY._serialized_start=234
  _HFTOKENIZERREQUEST_PARAMETERSENTRY._serialized_end=283
  _HFTOKENIZERREQUEST_PAYLOADENTRY._serialized_start=285
  _HFTOKENIZERREQUEST_PAYLOADENTRY._serialized_end=331
  _HFTOKENIZERRESPONSE._serialized_start=334
  _HFTOKENIZERRESPONSE._serialized_end=590
  _HFTOKENIZERRESPONSE_PAYLOADENTRY._serialized_start=285
  _HFTOKENIZERRESPONSE_PAYLOADENTRY._serialized_end=331
  _HFTOKENIZERRESPONSE_EXTRASENTRY._serialized_start=545
  _HFTOKENIZERRESPONSE_EXTRASENTRY._serialized_end=590
  _HFTOKENIZERPUSHREQUEST._serialized_start=592
  _HFTOKENIZERPUSHREQUEST._serialized_end=655
  _HFTOKENIZERPUSHRESPONSE._serialized_start=657
  _HFTOKENIZERPUSHRESPONSE._serialized_end=711
  _HFPREPROCESSOR._serialized_start=714
  _HFPREPROCESSOR._serialized_end=938
# @@protoc_insertion_point(module_scope)
