name: moviedata_offline_evaluate_emb
working_dir: ./src
python: /opt/anaconda3/envs/pytorch-1.10.1/bin/python

pipeline:

- 
  name: item_train_encode
  status: 1
  script: item_model/item_offline_embed.py
  args:
    item_data: ../data/moviedata-10m-schema/item.train.json
    dump_data: ../data/moviedata-10m-dump/item.emb.train.pkl
    text_model_name: DMetaSoul/sbert-chinese-general-v2
    batch_size: 512
    device: "cuda:0"

- 
  name: item_test_encode
  status: 1
  script: item_model/item_offline_embed.py
  args:
    item_data: ../data/moviedata-10m-schema/item.test.json
    dump_data: ../data/moviedata-10m-dump/item.emb.test.pkl
    text_model_name: DMetaSoul/sbert-chinese-general-v2
    batch_size: 512
    device: "cuda:0"

-
  name: user_encode
  status: 1
  script: user_model/user_offline_embed.py
  args:
    scene_id: douban-cb-100
    action_type: rating
    action_data: ../data/moviedata-10m-schema/action.train.json
    item_data: ../data/moviedata-10m-dump/item.emb.train.pkl
    dump_data: ../data/moviedata-10m-dump/user.emb.train.pkl
    action_sortby_key: action_time
    action_agg_func: avg
    action_max_len: 3
    action_decay_rate: 0.5

-
  name: search
  status: 1
  script: search/semantic_search.py
  args:
    user_data: ../data/moviedata-10m-dump/user.emb.train.pkl
    item_data: ../data/moviedata-10m-dump/item.emb.test.pkl
    result_data: ../data/moviedata-10m-dump/search_result.emb.json
    topk: 20

-
  name: evaluate
  status: 1
  script: search/evaluate.py
  args:
    scene_id: douban-cb-100
    action_type: rating
    action_sortby_key: action_time
    action_data: ../data/moviedata-10m-schema/action.test.json
    predict_data: ../data/moviedata-10m-dump/search_result.emb.json
    result_data: ../data/moviedata-10m-dump/evaluate_result.emb.json
    topk: 20
