name: moviedata_offline_evaluate_tag
working_dir: ./src
python: /opt/anaconda3/envs/pytorch-1.10.1/bin/python

pipeline:

- 
  name: item_train_encode
  status: 1
  script: item_model/item_offline_tag.py
  args:
    item_data: ../data/moviedata-10m-schema/item.train.json
    dump_data: ../data/moviedata-10m-dump/item.tag.train.pkl

- 
  name: item_test_encode
  status: 1
  script: item_model/item_offline_tag.py
  args:
    item_data: ../data/moviedata-10m-schema/item.test.json
    dump_data: ../data/moviedata-10m-dump/item.tag.test.pkl

-
  name: user_encode
  status: 1
  script: user_model/user_offline_tag.py
  args:
    scene_id: douban-cb-100
    action_type: rating
    action_data: ../data/moviedata-10m-schema/action.train.json
    item_data: ../data/moviedata-10m-schema/item.train.json
    dump_data: ../data/moviedata-10m-dump/user.tag.train.json
    action_sortby_key: action_time
    action_max_len: 3

-
  name: search
  status: 1
  script: search/tag_search.py
  args:
    user_data: ../data/moviedata-10m-dump/user.tag.train.json
    item_data: ../data/moviedata-10m-dump/item.tag.test.pkl
    result_data: ../data/moviedata-10m-dump/search_result.tag.json
    topk: 20

-
  name: evaluate
  status: 1
  script: search/evaluate.py
  args:
    scene_id: douban-cb-100
    action_type: rating
    action_sortby_key: action_time
    action_data: ../data/moviedata-10m-schema/action.test.json
    predict_data: ../data/moviedata-10m-dump/search_result.tag.json
    result_data: ../data/moviedata-10m-dump/evaluate_result.tag.json
    topk: 20
