name: movielens_offline_emb
working_dir: ./src
python: /opt/anaconda3/envs/pytorch-1.10.1/bin/python

pipeline:

- 
  name: item_encode
  status: 1
  script: item_model/item_offline_embed.py
  args:
    item_data: ../data/ml-1m-schema/item.train.json
    dump_data: ../data/ml-1m-dump/item.emb.pkl
    text_model_name: sentence-transformers/all-MiniLM-L6-v2
    batch_size: 64
    device: "cuda:0"

-
  name: user_encode
  status: 1
  script: user_model/user_offline_embed.py
  args:
    scene_id: ml-cb-100
    action_type: rating
    action_data: ../data/ml-1m-schema/action.train.json
    item_data: ../data/ml-1m-dump/item.emb.pkl
    dump_data: ../data/ml-1m-dump/user.emb.pkl
    action_sortby_key: action_time
    action_agg_func: avg
    action_max_len: 3
    action_decay_rate: 0.5

-
  name: push_item
  status: 1
  script: milvus/push.py
  args:
    host: 10.0.1.85
    port: 19530
    collection_name: movielens_cb_demo
    id_field: _ids
    emb_field: embs
    index_field: item_emb
    index_file: ../data/ml-1m-dump/item.emb.pkl

-
  name: push_item_test
  status: 1
  script: milvus/pull.py
  args:
    host: 10.0.1.85
    port: 19530
    collection_name: movielens_cb_demo
    index_field: item_emb
    vector: 384

-
  name: push_user
  status: 1
  script: mongo/push.py
  args:
    uri: mongodb://172.31.37.47:27017
    db_name: jpa
    collection_name: movielens_cb_demo
    id_field: _ids
    emb_field: embs
    index_file: ../data/ml-1m-dump/user.emb.pkl

-
  name: push_user_test
  status: 1
  script: mongo/pull.py
  args:
    uri: mongodb://172.31.37.47:27017
    db_name: jpa
    collection_name: movielens_cb_demo
