## spark session
app_name: 'Multi-task Demo MMoE'
local: True
worker_count: 1
server_count: 1
batch_size: 128 #32
worker_memory: '5G'
server_memory: '5G'
coordinator_memory: '5G'

## datasets
train_path: s3://dmetasoul-bucket/demo/census/train_data.csv
test_path: s3://dmetasoul-bucket/demo/census/test_data.csv

## model configurations
column_name_path: s3://dmetasoul-bucket/demo/multitask/schema/mmoe/column_name
combine_schema_path: s3://dmetasoul-bucket/demo/multitask/schema/mmoe/combine_schema

model_in_path: null
model_out_path: s3://dmetasoul-bucket/demo/multitask/model/mmoe/model_out/census/
model_export_path: s3://dmetasoul-bucket/demo/multitask/model/mmoe/model_export/census/
model_version: '0.1'
experiment_name: multitask_mmoe_census
input_label_column_indexes: [0, 1]
task_numb: 2
metric_update_interval: 100
training_epoches: 100
shuffle_training_dataset: True

## model hyper params
embedding_dim: 2
expert_numb: 2
expert_hidden_units: []
expert_out_dim: 4
gate_hidden_units: []
tower_hidden_units: []
dnn_activations: ReLU
use_bias: True
input_norm: True
batch_norm: True
net_dropout: null
net_regularizer: null
sparse_init_var: 0.01
adam_learning_rate: 0.000001
ftrl_l1: 1.0
ftrl_l2: 120.0
ftrl_alpha: 0.5
ftrl_beta: 1.0