## spark session
app_name: 'WideDeep Demo'
local: False
worker_count: 4
server_count: 4
batch_size: 50
worker_memory: '10G'
server_memory: '10G'
coordinator_memory: '10G'

## datasets
train_path: s3://dmetasoul-bucket/demo/criteo_x1/train_5.parquet
test_path: s3://dmetasoul-bucket/demo/criteo_x1/test_1.parquet

## model configurations
column_name_path: s3://dmetasoul-bucket/demo/schema/column_name_demo.txt
combine_schema_path: s3://dmetasoul-bucket/demo/schema/combine_schema_demo.txt
wide_combine_schema_path: s3://dmetasoul-bucket/demo/schema/combine_schema_demo.txt

model_in_path: null
model_out_path: s3://dmetasoul-bucket/demo/movielens/model/widedeep/model_out/criteo_d5/
model_export_path: s3://dmetasoul-bucket/demo/movielens/model/widedeep/model_export/criteo_d5/
model_version: '0.1'
experiment_name: criteo_wdl_d5
input_label_column_index: 0

## model hyper params
embedding_size: 10
net_dropout: 0.0
adam_learning_rate: 0.00001
ftrl_l1: 1.0
ftrl_l2: 120.0
ftrl_alpha: 0.01
ftrl_beta: 1.0
dnn_hidden_units: [1024,512,256,128]