apiVersion: metaspore/v1
kind: TrainingJob
metadata:
  name: WideDeep
  category: Rank/DeepCTR/WideDeep

spec:
  logging:
    loglevel: {{loglevel | default('debug')}}

  spark:
    session_confs:
      app_name: Ecommerce Deep CTR Pipeline
      local: {{local | default(True)}}
      worker_count: {{worker_count | default(1)}}
      worker_cpu: {{worker_cpu | default(1)}}
      server_count: {{server_count | default(1)}}
      server_cpu: {{server_cpu | default(1)}}
      batch_size: {{batch_size | default(256)}}
      worker_memory: {{worker_memory | default('4G')}}
      server_memory: {{server_memeory | default('4G')}}
      coordinator_memory: {{coordinator_memory | default('2G')}}
    extended_confs:
      spark.network.timeout: '500'
      spark.ui.showConsoleProgress: 'true'
      spark.kubernetes.executor.deleteOnTermination: 'true'

  dataset:
    train_path: {{train_path}} 
    test_path: {{test_path}}

  training:
    deep_ctr_model_class: metaspore.algos.widedeep_net.WideDeep
    estimator_config_class: metaspore.algos.pipeline.DeepCTREstimatorConfig
    model_config_class: metaspore.algos.pipeline.WideDeepConfig
    model_params: 
      wide_column_name_path: {{wide_column_name_path}}
      wide_combine_schema_path: {{wide_combine_schema_path}}
      deep_column_name_path: {{deep_column_name_path}}
      deep_combine_schema_path: {{deep_combine_schema_path}}
      use_wide: True
      use_dnn: True
      wide_embedding_dim: 16
      deep_embedding_dim: 16
      ftrl_l1: 1.0
      ftrl_l2: 120.0
      ftrl_alpha: 1.0
      ftrl_beta: 1.0
      dnn_hidden_units: [256, 256, 256]
      sparse_init_var: 0.01
      dnn_hidden_activations: ReLU
      use_bias: True
      batch_norm: True
      net_dropout: 0
      net_regularizer: null
    
    estimator_params:
      model_in_path: null
      model_out_path: {{base_dir}}/output/model/ctr/nn/widedeep/model_out/{{rank_deepctr_online_name}}
      model_export_path: {{base_dir}}/output/model/ctr/nn/widedeep/model_export/{{rank_deepctr_online_name}}
      model_version: '0.1'
      experiment_name: {{rank_deepctr_online_name}} 
      input_label_column_index: 0
      metric_update_interval: 100
      adam_learning_rate: 0.0001
      training_epoches: 1
      shuffle_training_dataset: True

