apiVersion: metaspore/v1
kind: Trainingjob
metadata:
  name: Popular
  category: Match/Popular

spec:
  logging:
    loglevel: {{loglevel | default('debug')}}

  spark:
    session_confs:
      app_name: 'Ecommerce Popular Pipeline Demo'
      local: {{local | default(True)}}
      worker_count: {{worker_count | default(1)}}
      worker_cpu: {{worker_cpu | default(1)}}
      server_count: {{server_count | default(1)}}
      server_cpu: {{server_cpu | default(1)}}
      batch_size: {{batch_size | default(256)}}
      worker_memory: {{worker_memory | default('4G')}}
      server_memory: {{server_memeory | default('4G')}}
      coordinator_memory: {{coordinator_memory | default('2G')}}
    extended_confs:
      spark.network.timeout: '500'
      spark.ui.showConsoleProgress: 'true'
      spark.kubernetes.executor.deleteOnTermination: 'true'
      spark.jars.packages: 'org.mongodb.spark:mongo-spark-connector_2.12:3.0.1'

  dataset:
    train_path: {{train_path}}
    fmt: {{dataset_fmt | default('parquet')}}

  training:
    estimator_params:
      max_recommendation_count: {{max_recommendation_count}}
      group_nums: 10
      model_out_path: null

  mongodb:
    uri: {{mongodb_uri}}
    database: {{mongodb_db}}
    collection: {{mongodb_collection}} 
    write_mode: overwrite
    index_fields: []
    index_unique: False
