apiVersion: metaspore/v1
kind: TrainingJob
metadata:
  name: Setup
  category: Setup

spec:
  logging:
    loglevel: debug

  init_spark:
    session_conf:
      app_name: 'Ecommerce Setup'
      local: {{local | default(True)}}
      worker_count: {{worker_count | default(1)}}
      worker_cpu: {{worker_cpu | default(1)}}
      server_count: {{server_count | default(1)}}
      server_cpu: {{server_cpu | default(1)}}
      batch_size: {{batch_size | default(256)}}
      worker_memory: {{worker_memory | default('4G')}}
      server_memory: {{server_memeory | default('4G')}}
      coordinator_memory: {{coordinator_memory | default('2G')}}
    extended_conf:
      spark.network.timeout: '500'
      spark.ui.showConsoleProgress: 'true'
      spark.kubernetes.executor.deleteOnTermination: 'true'
      

  load_dataset:
    format: jdbc
    driver: com.mysql.jdbc.Driver
    host: {{db_host | default("localhost")}}
    port: {{db_port | default("3306")}}
    database: {{db_name | default("metaspore_offline_flow")}}
    user_table: {{db_user_tbl | default("user")}}
    item_table: {{db_item_tbl | default("item")}}
    interaction_table: {{db_iteraction_tbl | default("interaction")}}
    user: {{db_username | default("root")}}
    password: {{db_password | default("test_mysql_123456")}}

  save_dataset:
    user_path: {{user_path}}
    item_path: {{item_path}}
    interaction_path: {{interaction_path}}
