apiVersion: metaspore/v1
kind: TrainingJob
metadata:
  name: ItemCF
  category: Match/I2I/Swing

spec:
  logging:
    loglevel: {{loglevel | default('debug')}}

  spark:
    session_confs:
      app_name: 'Ecommerce Swing I2I Pipeline'
      local: {{local | default(True)}}
      worker_count: {{worker_count | default(1)}}
      worker_cpu: {{worker_cpu | default(2)}}
      server_count: {{server_count | default(1)}}
      server_cpu: {{server_cpu | default(2)}}
      batch_size: {{batch_size | default(256)}}
      worker_memory: {{worker_memory | default('4G')}}
      server_memory: {{server_memeory | default('4G')}}
      coordinator_memory: {{coordinator_memory | default('2G')}}
    extended_confs:
      spark.network.timeout: '500'
      spark.ui.showConsoleProgress: 'true'
      spark.kubernetes.executor.deleteOnTermination: 'true'
      spark.jars.packages: 'org.mongodb.spark:mongo-spark-connector_2.12:3.0.1'

  dataset: 
    train_path: {{train_path}}
    test_path: {{test_path}}
    fmt: {{dataset_fmt | default('parquet')}}

  training: 
    i2i_estimator_class: {{training_estimator}}
    i2i_estimator_config_class: {{training_estimator_config}}
    estimator_params:
      max_recommendation_count: {{max_recommendation_count}}

  mongodb: 
    uri: {{mongodb_uri}}
    database: {{mongodb_db}}
    write_mode: overwrite
    index_fields: []
    index_unique: False
    collection: {{mongodb_collection}}
