app_name: SimpleX Tuner
num_experiment: 20
model_name: simplex
result_path: ${MY_S3_BUCKET}/tuner/model/simplex/
local_result_path: './output'
py_files: 'python.zip'

dataset:
    train: ${MY_S3_BUCKET}/movielens/match/num_negs_100/train.parquet
    test: ${MY_S3_BUCKET}/movielens/match/num_negs_100/test.parquet
    item: ${MY_S3_BUCKET}/movielens/match/num_negs_100/item.parquet

common_param:
    worker_count: 2
    server_count: 2
    user_column_name: ${MY_S3_BUCKET}/movielens/config/simplex/user_column_schema
    user_combine_schema: ${MY_S3_BUCKET}/movielens/config/simplex/user_combine_schema
    interacted_items_combine_schema: ${MY_S3_BUCKET}/movielens/config/simplex/interacted_items_combine_schema
    item_column_name: ${MY_S3_BUCKET}/movielens/config/simplex/item_column_schema
    item_combine_schema: ${MY_S3_BUCKET}/movielens/config/simplex/item_combine_schema
    itemdb_combine_schema: ${MY_S3_BUCKET}/movielens/config/simplex/itemdb_combine_schema
    model_in_path: null
    model_out_path: ${MY_S3_BUCKET}/movielens/model/simplex/model_out/
    model_export_path: null
    model_version: null
    experiment_name: null
    input_label_column_index: 0
    item_ids_column_indices: [6]
    retrieval_item_count: 20
    metric_update_interval: 500
    

hyper_param:
    _negative_sample_count: 13
    _w: 3
    _m: [0.8, 0.9]
    net_dropout: 0
    batch_size: [256, 512]
    embedding_size: 32
    gamma: [0.7, 0.8, 0.9]
    #adam_learning_rate: eval@10**(-(2+np.random.rand()*2))
    adam_learning_rate: [0.001, 0.002, 0.003]
    ftrl_learning_rate: 0.02
    ftrl_smothing_rate: 1.0
    ftrl_l1_regularization: 1.0
    ftrl_l2_regularization: 1.0
    training_epoches: [1, 2]
    shuffle_training_dataset: True
