## spark session
app_name: 'Pipeline Demo'
local: False
worker_count: 2
server_count: 2
batch_size: 128
worker_memory: '4G'
server_memory: '4G'
coordinator_memory: '4G'

zip_path: ../MetaSpore/solutions/recommend/offline/social_network/python.zip
zip_cwd: ../../../../../recommend-algos

## datasets
train_path: s3://dmetasoul-bucket/demo/datasets/soc-pokec/demo_fg/train_dataset.parquet
test_path: s3://dmetasoul-bucket/demo/datasets/soc-pokec/demo_fg/test_dataset.parquet
item_path: s3://dmetasoul-bucket/demo/datasets/soc-pokec/demo_fg/item_dataset.parquet

user_id: user_id
item_id: friend_id

## model configuratio
two_tower_module: metaspore
# two_tower_module: python.two_tower_retrieval_milvus 
two_tower_module_class: TwoTowerBatchNegativeSamplingModule
two_tower_estimator_class: TwoTowerRetrievalEstimator

user_column_name: s3://dmetasoul-bucket/demo/datasets/soc-pokec/demo_schema/column_name.txt
user_combine_schema: s3://dmetasoul-bucket/demo/datasets/soc-pokec/demo_schema/user_combine_schema.txt
item_column_name: s3://dmetasoul-bucket/demo/datasets/soc-pokec/demo_schema/column_name.txt
item_combine_schema: s3://dmetasoul-bucket/demo/datasets/soc-pokec/demo_schema/item_combine_schema.txt
model_in_path: null
model_out_path: s3://dmetasoul-bucket/demo/soc-pokec/model/dssm/model_out/
# model_export_path: s3://dmetasoul-bucket/demo/soc-pokec/model/dssm/model_export/
model_export_path: null
model_version: '0.1'
experiment_name: soc_pokec_two_towers_dssm

## milvus
milvus_description: 'ml_1m_dssm'
milvus_host: 'my-milvus-release.milvus.svc.cluster.local'
milvus_port: '19530'
milvus_embedding_field: 'embedding_vector'
milvus_index_type: 'IVF_FLAT'
milvus_metric_type: 'IP'
milvus_nlist: 1024
milvus_nprobe: 128


## dataset
input_label_column_index: 0
input_feature_column_num: 8
input_item_id_column_index: 2 
input_item_probability_column_index: -1
input_sample_weight_column_index: -1

## model hyper params
tau: 0.05
use_remove_accidental_hits: True
use_sampling_probability_correction: False
use_sample_weight: False
vector_embedding_size: 16
item_embedding_size: 64
net_dropout: 0.0
dense_structure: [256, 128, 64]
adam_learning_rate: 0.00001
ftrl_learning_rate: 0.02
ftrl_smothing_rate: 1.0
ftrl_l1_regularization: 1.0
ftrl_l2_regularization: 1.0
training_epoches: 1
shuffle_training_dataset: True
