logging:
  loglevel: debug

spark:
  node_class: InitSparkNode
  node_priority: 10
  session_confs:
    app_name: 'I2I Pipeline Demo'
    local: False
    worker_count: 2
    worker_cpu: 4
    server_count: 2
    server_cpu: 4
    batch_size: 128
    worker_memory: '10G'
    server_memory: '10G'
    coordinator_memory: '10G'

  extended_confs:
    spark.network.timeout: '500'
    spark.ui.showConsoleProgress: 'true'
    spark.kubernetes.executor.deleteOnTermination: 'true'
  
  pyzip:
    cwd_path: '/home/spark/work/MetaSpore/'
    zip_file_path: '/home/spark/work/MetaSpore/solutions/recommend/offline/python.zip'

dataset:
  node_class: DataLoaderNode
  node_priority: 20
  train_path: s3://dmetasoul-bucket/demo/datasets/soc-pokec/demo_fg/train_dataset.parquet
  test_path: s3://dmetasoul-bucket/demo/datasets/soc-pokec/demo_fg/test_dataset.parquet
  item_path: s3://dmetasoul-bucket/demo/datasets/soc-pokec/demo_fg/item_dataset.parquet
  user_id_column: user_id
  item_id_column: friend_id
  label_column: label
  label_value: '1'
  last_item_id_column: last_friend_id

training:
  node_class: I2IEstimatorNode
  node_priority: 30
  i2i_estimator_class:
    module_name: python.algos.item_cf_retrieval
    class_name: ItemCFEstimator

#  i2i_estimator_class:
#    module_name: metaspore
#    class_name: SwingEstimator
    
  model_out_path: s3://dmetasoul-bucket/demo/soc-pokec/model/item_cf/model_out/df.parquet
  max_recommendation_count: 20
  
evaluation:
  node_class: RetrievalEvaluatorNode
  node_priority: 40
  
mongodb:
  node_class: MongoDBDumperNode
  node_priority: 50
  input_url: mongodb://jpa:Dmetasoul_123456@172.31.37.47:27017/jpa.saas_icf
  output_url: mongodb://jpa:Dmetasoul_123456@172.31.37.47:27017/jpa.saas_icf

spark_stop:
  node_class: StopSparkNode
  node_priority: 99
  