logging:
  loglevel: info

spark:
  session_confs:
    app_name: 'Pipeline Demo'
    local: True
    batch_size: 128
    worker_count: 2
    server_count: 2
    worker_cpu: 4
    server_cpu: 4
    worker_memory: '4G'
    server_memory: '4G'
    coordinator_memory: '4G'

  extended_confs:
    spark.network.timeout: '500'
    spark.ui.showConsoleProgress: 'true'
    spark.kubernetes.executor.deleteOnTermination: 'true'
  
  pyzip:
    cwd_path: '/home/spark/work/recommend-algos/'
    zip_file_path: '/home/spark/work/MetaSpore/solutions/recommend/offline/python.zip'
