logging:
  loglevel: debug

spark:
  node_class: InitSparkNode
  node_priority: 10
  session_confs:
    app_name: 'Pipeline Demo'
    local: False
    worker_count: 2
    worker_cpu: 4
    server_count: 2
    server_cpu: 4
    batch_size: 128
    worker_memory: '10G'
    server_memory: '10G'
    coordinator_memory: '10G'

  extended_confs:
    spark.network.timeout: '500'
    spark.ui.showConsoleProgress: 'true'
    spark.kubernetes.executor.deleteOnTermination: 'true'
  
  pyzip:
    cwd_path: '/home/spark/work/recommend-algos/'
    zip_file_path: '/home/spark/work/MetaSpore/solutions/recommend/offline/python.zip'

dataset:
  node_class: DataLoaderNode
  node_priority: 20
  train_path: s3://dmetasoul-bucket/demo/datasets/soc-pokec/demo_fg/train_dataset.parquet
  test_path: s3://dmetasoul-bucket/demo/datasets/soc-pokec/demo_fg/test_dataset.parquet
  item_path: s3://dmetasoul-bucket/demo/datasets/soc-pokec/demo_fg/item_dataset.parquet
  user_id_column: user_id
  item_id_column: friend_id
  label_column: label
  label_value: '1'
  last_item_id_column: last_friend_id

training:
  node_class: TwoTowersEstimatorNode
  node_priority: 30
  user_module_class:
    module_name: python.dssm_net
    class_name: UserModule
  
  item_module_class:
    module_name: python.dssm_net
    class_name: ItemModule
  
  similarity_module_class:
    module_name: python.dssm_net
    class_name: SimilarityModule

  two_towers_retrieval_module_class:
    module_name: python.training
    class_name: TwoTowerBatchNegativeSamplingModule

  two_towers_agent_class:
    module_name: python.training
    class_name: TwoTowerBatchNegativeSamplingAgent
  
  two_towers_estimator_class:
    module_name: metaspore
    class_name: TwoTowerRetrievalEstimator

  user_column_name: s3://dmetasoul-bucket/demo/datasets/soc-pokec/demo_schema/column_name.txt
  user_combine_schema: s3://dmetasoul-bucket/demo/datasets/soc-pokec/demo_schema/user_combine_schema.txt
  item_column_name: s3://dmetasoul-bucket/demo/datasets/soc-pokec/demo_schema/column_name.txt
  item_combine_schema: s3://dmetasoul-bucket/demo/datasets/soc-pokec/demo_schema/item_combine_schema.txt
  model_in_path: null
  model_out_path: s3://dmetasoul-bucket/demo/soc-pokec/model/dssm/model_out/
  # model_export_path: s3://dmetasoul-bucket/demo/soc-pokec/model/dssm/model_export/
  model_export_path: null
  model_version: '0.1'
  experiment_name: soc_pokec_two_towers_dssm

  item_ids_column_indices: [2]
  retrieval_item_count: 20
  metric_update_interval: 500

  ## dataset
  input_label_column_index: 0
  input_feature_column_num: 8
  input_item_id_column_index: 2 
  input_item_probability_column_index: -1
  input_sample_weight_column_index: -1

  ## model hyper params
  tau: 0.05
  use_remove_accidental_hits: True
  use_sampling_probability_correction: False
  use_sample_weight: False
  vector_embedding_size: 16
  item_embedding_size: 64
  net_dropout: 0.0
  dense_structure: [256, 128, 64]
  adam_learning_rate: 0.00001
  ftrl_learning_rate: 0.02
  ftrl_smothing_rate: 1.0
  ftrl_l1_regularization: 1.0
  ftrl_l2_regularization: 1.0
  training_epoches: 1
  shuffle_training_dataset: True

evaluation:
  node_class: RetrievalEvaluatorNode
  node_priority: 40

spark_stop:
  node_class: StopSparkNode
  node_priority: 99