## spark session
app_name: 'Global Hot'
local: False
worker_count: 4
server_count: 4
batch_size: 512
worker_memory: '10G'
server_memory: '10G'
coordinator_memory: '10G'

## dataset
train_path: ${MY_S3_BUCKET}/movielens/1m/cf/train.parquet
test_path: ${MY_S3_BUCKET}/demo/movielens/1m/negsample/num_negs_10/test.parquet

## recall configuration
max_recommendation_count: 20
